### ISSUE TITLE
When the Show customView layout cannot be used

### ISSUE THREAD

**Issue by 651893553** [andreamazz/AMPopTip#70] opened 2016-05-12 06:45 UTC
When a XIB custom view, aotulayout can't use, for the first time show popTipView is normal, but closed again after opening will cause a suspended animation!

- (void)layoutSubviews {
    [super layoutSubviews];
    [self setup];
}
- (void)setup {

}

These two methods will call cycles

- (void)show {
    if (self.isVisible || self.isAnimating) {
        return;
    }
    self.isAnimating = YES;
    [self setNeedsLayout];
    [self performEntranceAnimation:^{
        [self.containerView addGestureRecognizer:self.tapRemoveGesture];
        [self.containerView addGestureRecognizer:self.swipeRemoveGesture];
        if (self.appearHandler) {
            self.appearHandler();
        }
        if (self.actionAnimation != AMPopTipActionAnimationNone) {
            [self startActionAnimation];
        }
        self.isVisible = YES;
        self.isAnimating = NO;
    }];
}

 [self performEntranceAnimation:^{
        
}];

This method of correction will not be invoked

**Comment by andreamazz** [comment] 2016-05-13 07:44
Checkout commit 171f0a8
It's a blind fix though, let me know

**Comment by 651893553** [comment] 2016-05-13 10:01
May be this is not a good solution, when quick click view back to the layout of the mistakes

**Comment by andreamazz** [comment] 2016-05-13 10:02
what?

**Comment by 651893553** [comment] 2016-05-13 10:07
I call on a tableview, quick click popTipView border half did not show

**Comment by andreamazz** [comment] 2016-05-13 10:12
...
Please provide a sample project showing the issue.

**Comment by andreamazz** [comment] 2016-05-19 09:20
I'm closing this since I can't really understand what the issue is. Feel free to reopen it once you have a small sample showing the problem.

**Closed by andreamazz** 2016-05-19 09:20 UTC
Labels: awaiting feedback
